'use client';
import { useEffect, useState } from 'react';
import { BookOpen, Loader2, ArrowUpCircle, ArrowDownCircle, MinusCircle, AlertCircle, RotateCcw } from 'lucide-react';
import { Header } from '@/components/layout/header';
import { Badge } from '@/components/ui/badge';
import { BranchSelector } from '@/components/branch-selector';
import { Label } from '@/components/ui/label';
import { transitionLedgerApi, transitionCreditsApi } from '@/lib/api';
import { formatCurrency, formatDate } from '@/lib/utils';
import { cn } from '@/lib/utils';

interface LedgerEntry {
  id: string; entryType: string; amount: string; referenceType?: string;
  referenceId?: string; notes?: string; isAutoGenerated: boolean; createdAt: string;
  transitionCreditLot?: { stockSnapshotItem?: { rawSku: string; rawDescription: string }; taxTransitionRule?: { name: string } };
}
interface Balance { totalGenerated: number; totalUsed: number; totalBlocked: number; totalAdjustments: number; available: number; }

const ENTRY_CONFIG: Record<string, { label: string; icon: React.ElementType; color: string }> = {
  GENERATED: { label: 'Gerado', icon: ArrowUpCircle, color: 'text-green-600' },
  USED: { label: 'Utilizado', icon: ArrowDownCircle, color: 'text-blue-600' },
  BLOCKED: { label: 'Bloqueado', icon: MinusCircle, color: 'text-red-600' },
  MANUAL_ADJUSTMENT: { label: 'Ajuste Manual', icon: AlertCircle, color: 'text-amber-600' },
  REVERSED: { label: 'Estornado', icon: RotateCcw, color: 'text-slate-600' },
};

export default function TransicaoLedgerPage() {
  const [entries, setEntries] = useState<LedgerEntry[]>([]);
  const [balance, setBalance] = useState<Balance | null>(null);
  const [loading, setLoading] = useState(true);
  const [branchId, setBranchId] = useState('');

  const load = (bid?: string) => {
    const id = bid ?? branchId;
    setLoading(true);
    Promise.all([
      transitionLedgerApi.list({ branchId: id || undefined, limit: 200 }).then(r => setEntries(r.entries ?? [])),
      id ? transitionCreditsApi.getBalance(id).then(setBalance) : Promise.resolve(setBalance(null)),
    ]).catch(() => { setEntries([]); setBalance(null); }).finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  const handleBranchChange = (id: string) => { setBranchId(id); load(id); };

  return (
    <div>
      <Header title="Extrato de Créditos" subtitle="Movimentações de créditos de transição ICMS-ST" />
      <div className="p-4 lg:p-6 space-y-5">
        {/* Filters */}
        <div className="flex flex-wrap items-end gap-4">
          <div className="flex-1 min-w-[240px] max-w-sm space-y-1.5">
            <Label className="text-xs text-slate-500">Filial</Label>
            <BranchSelector value={branchId} onChange={handleBranchChange} placeholder="Todas as filiais" />
          </div>
        </div>

        {/* Balance cards */}
        {balance && (
          <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">
            {[
              { label: 'Total Gerado', value: balance.totalGenerated, color: 'bg-green-50 border-green-100 text-green-700' },
              { label: 'Utilizado', value: balance.totalUsed, color: 'bg-blue-50 border-blue-100 text-blue-700' },
              { label: 'Bloqueado', value: balance.totalBlocked, color: 'bg-red-50 border-red-100 text-red-600' },
              { label: 'Ajustes', value: balance.totalAdjustments, color: 'bg-amber-50 border-amber-100 text-amber-700' },
              { label: 'Saldo Disponível', value: balance.available, color: 'bg-emerald-50 border-emerald-200 text-emerald-700' },
            ].map(c => (
              <div key={c.label} className={cn('rounded-2xl border p-4 text-center', c.color)}>
                <p className="text-xl font-bold">{formatCurrency(c.value)}</p>
                <p className="text-xs mt-1">{c.label}</p>
              </div>
            ))}
          </div>
        )}

        {/* Ledger entries */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="p-5 border-b border-slate-100">
            <p className="font-semibold text-slate-800">Extrato ({entries.length} movimentações)</p>
          </div>
          {loading ? (
            <div className="p-8 text-center text-slate-400"><Loader2 className="h-5 w-5 animate-spin mx-auto mb-2" />Carregando...</div>
          ) : entries.length === 0 ? (
            <div className="p-8 text-center text-slate-400"><BookOpen className="h-8 w-8 mx-auto mb-2 opacity-40" /><p className="text-sm">Nenhuma movimentação encontrada</p></div>
          ) : (
            <div className="divide-y divide-slate-50">
              {entries.map(e => {
                const cfg = ENTRY_CONFIG[e.entryType] ?? { label: e.entryType, icon: AlertCircle, color: 'text-slate-600' };
                const Icon = cfg.icon;
                const amount = parseFloat(e.amount);
                const lot = e.transitionCreditLot;
                return (
                  <div key={e.id} className="flex items-start gap-3 px-5 py-3.5 hover:bg-slate-50 transition-colors">
                    <Icon className={cn('h-5 w-5 flex-shrink-0 mt-0.5', cfg.color)} />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-0.5">
                        <span className={cn('text-sm font-semibold', cfg.color)}>{cfg.label}</span>
                        {!e.isAutoGenerated && <Badge variant="outline" className="text-xs">Manual</Badge>}
                      </div>
                      {lot?.stockSnapshotItem && (
                        <p className="text-xs text-slate-500 truncate">
                          {lot.stockSnapshotItem.rawSku} — {lot.stockSnapshotItem.rawDescription}
                        </p>
                      )}
                      {e.notes && <p className="text-xs text-slate-400 mt-0.5">{e.notes}</p>}
                    </div>
                    <div className="flex-shrink-0 text-right">
                      <p className={cn('text-sm font-bold', amount >= 0 ? 'text-green-700' : 'text-red-600')}>
                        {amount >= 0 ? '+' : ''}{formatCurrency(amount)}
                      </p>
                      <p className="text-xs text-slate-400 mt-0.5">{formatDate(e.createdAt)}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
