-- CreateEnum
CREATE TYPE "CatalogAutoMode" AS ENUM ('DISABLED', 'CREATE_MISSING', 'CREATE_AND_ENRICH');

-- CreateEnum
CREATE TYPE "AutoImportProvider" AS ENUM ('NONE', 'IMAP', 'SFTP', 'DFE_SEFAZ');

-- CreateEnum
CREATE TYPE "AutomationRunStatus" AS ENUM ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "hasSeenOnboarding" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "onboardingDismissedAt" TIMESTAMP(3),
ADD COLUMN     "onboardingVersion" INTEGER NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "system_settings" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "catalogAutoModeStock" "CatalogAutoMode" NOT NULL DEFAULT 'CREATE_MISSING',
    "catalogAutoModeNfe" "CatalogAutoMode" NOT NULL DEFAULT 'CREATE_MISSING',
    "catalogAutoAliasByEan" BOOLEAN NOT NULL DEFAULT true,
    "catalogAutoAliasBySku" BOOLEAN NOT NULL DEFAULT true,
    "catalogAutoEnrichDesc" BOOLEAN NOT NULL DEFAULT false,
    "autoMatchAfterStockImport" BOOLEAN NOT NULL DEFAULT false,
    "autoMatchAfterNfeImport" BOOLEAN NOT NULL DEFAULT false,
    "autoOpenIssuesOnNoMatch" BOOLEAN NOT NULL DEFAULT true,
    "matchConfidenceThreshold" DOUBLE PRECISION NOT NULL DEFAULT 0.75,
    "autoCalcAfterMatching" BOOLEAN NOT NULL DEFAULT false,
    "autoGenerateDossier" BOOLEAN NOT NULL DEFAULT false,
    "autoSelectLatestSnapshot" BOOLEAN NOT NULL DEFAULT true,
    "autoSelectActiveRule" BOOLEAN NOT NULL DEFAULT true,
    "nfeManualImportEnabled" BOOLEAN NOT NULL DEFAULT true,
    "nfeAutoImportEnabled" BOOLEAN NOT NULL DEFAULT false,
    "nfeAutoImportProvider" "AutoImportProvider" NOT NULL DEFAULT 'NONE',
    "nfeAutoImportInterval" INTEGER NOT NULL DEFAULT 60,
    "nfeDefaultBranchId" TEXT,
    "imapHost" TEXT,
    "imapPort" INTEGER,
    "imapSsl" BOOLEAN NOT NULL DEFAULT true,
    "imapUser" TEXT,
    "imapPassword" TEXT,
    "imapMailbox" TEXT DEFAULT 'INBOX',
    "sftpHost" TEXT,
    "sftpPort" INTEGER,
    "sftpUser" TEXT,
    "sftpPassword" TEXT,
    "sftpDirectory" TEXT,
    "sftpProcessedDir" TEXT,
    "dfeCertificateKey" TEXT,
    "dfeCertificatePassword" TEXT,
    "dfeEnvironment" TEXT DEFAULT 'production',
    "notifyImportCompleted" BOOLEAN NOT NULL DEFAULT true,
    "notifyDuplicates" BOOLEAN NOT NULL DEFAULT false,
    "notifyParsingErrors" BOOLEAN NOT NULL DEFAULT true,
    "notifyOpenIssues" BOOLEAN NOT NULL DEFAULT true,
    "notifyCalcCompleted" BOOLEAN NOT NULL DEFAULT true,
    "lastAutoImportAt" TIMESTAMP(3),
    "lastAutoImportStatus" TEXT,
    "autoImportDocsImported" INTEGER NOT NULL DEFAULT 0,
    "autoImportDocsDuplicate" INTEGER NOT NULL DEFAULT 0,
    "autoImportDocsError" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "system_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "automation_runs" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "status" "AutomationRunStatus" NOT NULL DEFAULT 'RUNNING',
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt" TIMESTAMP(3),
    "totalProcessed" INTEGER NOT NULL DEFAULT 0,
    "totalImported" INTEGER NOT NULL DEFAULT 0,
    "totalDuplicate" INTEGER NOT NULL DEFAULT 0,
    "totalErrors" INTEGER NOT NULL DEFAULT 0,
    "errorMessage" TEXT,
    "payload" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "automation_runs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "system_settings_companyId_key" ON "system_settings"("companyId");

-- CreateIndex
CREATE INDEX "automation_runs_companyId_idx" ON "automation_runs"("companyId");

-- CreateIndex
CREATE INDEX "automation_runs_type_idx" ON "automation_runs"("type");

-- CreateIndex
CREATE INDEX "automation_runs_createdAt_idx" ON "automation_runs"("createdAt");

-- AddForeignKey
ALTER TABLE "system_settings" ADD CONSTRAINT "system_settings_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE;
