'use client';
import { useEffect, useState } from 'react';
import { Settings, FileText, Package, GitMerge, Calculator, Bell, Loader2, RefreshCw, Mail, FolderSync, Shield } from 'lucide-react';
import { Header } from '@/components/layout/header';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/components/ui/toast';
import { api } from '@/lib/api';
import { cn } from '@/lib/utils';

interface SettingsData {
  [key: string]: unknown;
  catalogAutoModeStock?: string;
  catalogAutoModeNfe?: string;
  catalogAutoAliasByEan?: boolean;
  catalogAutoAliasBySku?: boolean;
  autoMatchAfterStockImport?: boolean;
  autoMatchAfterNfeImport?: boolean;
  autoOpenIssuesOnNoMatch?: boolean;
  autoCalcAfterMatching?: boolean;
  autoGenerateDossier?: boolean;
  nfeManualImportEnabled?: boolean;
  nfeAutoImportEnabled?: boolean;
  nfeAutoImportProvider?: string;
  nfeAutoImportInterval?: number;
  imapHost?: string;
  imapPort?: number;
  imapSsl?: boolean;
  imapUser?: string;
  imapPassword?: string;
  notifyImportCompleted?: boolean;
  notifyParsingErrors?: boolean;
  notifyOpenIssues?: boolean;
  notifyCalcCompleted?: boolean;
  lastAutoImportAt?: string;
  lastAutoImportStatus?: string;
}

function Toggle({ value, onChange, label, desc }: { value: boolean; onChange: (v: boolean) => void; label: string; desc?: string }) {
  return (
    <div className="flex items-center justify-between p-3 rounded-xl bg-slate-50 border border-slate-200">
      <div>
        <p className="text-sm font-medium text-slate-700">{label}</p>
        {desc && <p className="text-xs text-slate-500 mt-0.5">{desc}</p>}
      </div>
      <button onClick={() => onChange(!value)} className={cn('relative w-11 h-6 rounded-full transition-colors', value ? 'bg-blue-500' : 'bg-slate-300')}>
        <span className={cn('absolute top-1 w-4 h-4 bg-white rounded-full shadow transition-all', value ? 'left-6' : 'left-1')} />
      </button>
    </div>
  );
}

export default function ConfiguracoesPage() {
  const { toast } = useToast();
  const [settings, setSettings] = useState<SettingsData>({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const load = () => {
    setLoading(true);
    api.get('/settings').then(r => setSettings(r.data ?? {})).catch(() => setSettings({})).finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  const save = async (partial: Partial<SettingsData>) => {
    setSaving(true);
    try {
      const res = await api.put('/settings', { ...partial });
      setSettings(res.data);
      toast({ type: 'success', title: 'Configurações salvas' });
    } catch { toast({ type: 'error', title: 'Erro ao salvar' }); }
    finally { setSaving(false); }
  };

  const updateField = (key: string, value: unknown) => {
    setSettings(prev => ({ ...prev, [key]: value }));
  };

  if (loading) return <div className="flex items-center justify-center h-64"><Loader2 className="h-6 w-6 animate-spin text-blue-500" /></div>;

  return (
    <div>
      <Header title="Configurações" subtitle="Configure automações e comportamentos do sistema" />
      <div className="p-4 lg:p-6 space-y-5">
        {/* NF-e Import */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="p-5 border-b border-slate-100 flex items-center gap-3">
            <FileText className="h-5 w-5 text-green-600" />
            <div><p className="font-semibold text-slate-900">Importação de NF-e</p><p className="text-xs text-slate-500">Configurações de importação manual e automática</p></div>
          </div>
          <div className="p-5 space-y-3">
            <Toggle value={settings.nfeManualImportEnabled !== false} onChange={v => updateField('nfeManualImportEnabled', v)} label="Importação manual habilitada" desc="Permite upload de XML pela interface" />
            <Toggle value={settings.nfeAutoImportEnabled === true} onChange={v => updateField('nfeAutoImportEnabled', v)} label="Importação automática" desc="Busca NF-e automaticamente em intervalo configurado" />

            {settings.nfeAutoImportEnabled && (
              <div className="ml-4 space-y-3 border-l-2 border-blue-200 pl-4">
                <div className="space-y-1.5">
                  <Label className="text-xs">Provedor</Label>
                  <select className="flex h-10 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm" value={settings.nfeAutoImportProvider ?? 'NONE'} onChange={e => updateField('nfeAutoImportProvider', e.target.value)}>
                    <option value="NONE">Nenhum (desativado)</option>
                    <option value="IMAP">E-mail / IMAP</option>
                    <option value="SFTP">SFTP / Pasta monitorada</option>
                    <option value="DFE_SEFAZ">DF-e / SEFAZ (certificado A1)</option>
                  </select>
                </div>

                {settings.nfeAutoImportProvider === 'IMAP' && (
                  <div className="space-y-3 rounded-xl bg-blue-50 border border-blue-100 p-4">
                    <p className="text-sm font-semibold text-blue-800 flex items-center gap-2"><Mail className="h-4 w-4" /> Configuração IMAP</p>
                    <div className="grid grid-cols-2 gap-3">
                      <div className="space-y-1"><Label className="text-xs">Host</Label><Input placeholder="imap.gmail.com" value={settings.imapHost ?? ''} onChange={e => updateField('imapHost', e.target.value)} /></div>
                      <div className="space-y-1"><Label className="text-xs">Porta</Label><Input type="number" placeholder="993" value={settings.imapPort ?? ''} onChange={e => updateField('imapPort', parseInt(e.target.value))} /></div>
                      <div className="space-y-1"><Label className="text-xs">Usuário</Label><Input placeholder="usuario@empresa.com" value={settings.imapUser ?? ''} onChange={e => updateField('imapUser', e.target.value)} /></div>
                      <div className="space-y-1"><Label className="text-xs">Senha</Label><Input type="password" value={settings.imapPassword ?? ''} onChange={e => updateField('imapPassword', e.target.value)} /></div>
                    </div>
                    <Toggle value={settings.imapSsl !== false} onChange={v => updateField('imapSsl', v)} label="SSL/TLS" />
                  </div>
                )}

                {settings.nfeAutoImportProvider === 'SFTP' && (
                  <div className="rounded-xl bg-amber-50 border border-amber-100 p-4">
                    <p className="text-sm font-semibold text-amber-800 flex items-center gap-2"><FolderSync className="h-4 w-4" /> SFTP</p>
                    <p className="text-xs text-amber-600 mt-1">Configuração de SFTP em breve. A estrutura está preparada no backend.</p>
                  </div>
                )}

                {settings.nfeAutoImportProvider === 'DFE_SEFAZ' && (
                  <div className="rounded-xl bg-purple-50 border border-purple-100 p-4">
                    <p className="text-sm font-semibold text-purple-800 flex items-center gap-2"><Shield className="h-4 w-4" /> DF-e / SEFAZ</p>
                    <p className="text-xs text-purple-600 mt-1">Integração com certificado A1 em breve. A estrutura está preparada no backend.</p>
                  </div>
                )}

                <div className="space-y-1">
                  <Label className="text-xs">Intervalo de sincronização (minutos)</Label>
                  <Input type="number" min={5} value={settings.nfeAutoImportInterval ?? 60} onChange={e => updateField('nfeAutoImportInterval', parseInt(e.target.value))} />
                </div>
              </div>
            )}

            {settings.lastAutoImportAt && (
              <div className="flex items-center gap-2 text-xs text-slate-500 pt-2 border-t border-slate-100">
                <RefreshCw className="h-3 w-3" />
                <span>Última execução: {new Date(settings.lastAutoImportAt).toLocaleString('pt-BR')}</span>
                <Badge variant={settings.lastAutoImportStatus === 'SUCCESS' ? 'success' : 'warning'} className="text-xs">{settings.lastAutoImportStatus}</Badge>
              </div>
            )}
          </div>
        </div>

        {/* Catalog */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="p-5 border-b border-slate-100 flex items-center gap-3">
            <Package className="h-5 w-5 text-blue-600" />
            <div><p className="font-semibold text-slate-900">Catálogo de Produtos</p><p className="text-xs text-slate-500">Criação automática de produtos durante importação</p></div>
          </div>
          <div className="p-5 space-y-3">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label className="text-xs">No import de estoque</Label>
                <select className="flex h-10 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm" value={settings.catalogAutoModeStock ?? 'CREATE_MISSING'} onChange={e => updateField('catalogAutoModeStock', e.target.value)}>
                  <option value="DISABLED">Desabilitado</option>
                  <option value="CREATE_MISSING">Criar produtos ausentes</option>
                  <option value="CREATE_AND_ENRICH">Criar e enriquecer dados</option>
                </select>
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">No import de NF-e</Label>
                <select className="flex h-10 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm" value={settings.catalogAutoModeNfe ?? 'CREATE_MISSING'} onChange={e => updateField('catalogAutoModeNfe', e.target.value)}>
                  <option value="DISABLED">Desabilitado</option>
                  <option value="CREATE_MISSING">Criar produtos ausentes</option>
                  <option value="CREATE_AND_ENRICH">Criar e enriquecer dados</option>
                </select>
              </div>
            </div>
            <Toggle value={settings.catalogAutoAliasByEan !== false} onChange={v => updateField('catalogAutoAliasByEan', v)} label="Criar alias por EAN automaticamente" />
            <Toggle value={settings.catalogAutoAliasBySku !== false} onChange={v => updateField('catalogAutoAliasBySku', v)} label="Criar alias por SKU normalizado" />
          </div>
        </div>

        {/* Conciliation */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="p-5 border-b border-slate-100 flex items-center gap-3">
            <GitMerge className="h-5 w-5 text-purple-600" />
            <div><p className="font-semibold text-slate-900">Conciliação</p><p className="text-xs text-slate-500">Automação do matching estoque x NF-e</p></div>
          </div>
          <div className="p-5 space-y-3">
            <Toggle value={settings.autoMatchAfterStockImport === true} onChange={v => updateField('autoMatchAfterStockImport', v)} label="Executar matching após importar estoque" />
            <Toggle value={settings.autoMatchAfterNfeImport === true} onChange={v => updateField('autoMatchAfterNfeImport', v)} label="Executar matching após importar NF-e" />
            <Toggle value={settings.autoOpenIssuesOnNoMatch !== false} onChange={v => updateField('autoOpenIssuesOnNoMatch', v)} label="Criar pendências quando faltar lastro" />
          </div>
        </div>

        {/* Calculation */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="p-5 border-b border-slate-100 flex items-center gap-3">
            <Calculator className="h-5 w-5 text-amber-600" />
            <div><p className="font-semibold text-slate-900">Cálculo ST</p><p className="text-xs text-slate-500">Automação de cálculos e dossiês</p></div>
          </div>
          <div className="p-5 space-y-3">
            <Toggle value={settings.autoCalcAfterMatching === true} onChange={v => updateField('autoCalcAfterMatching', v)} label="Executar cálculo ST após matching" />
            <Toggle value={settings.autoGenerateDossier === true} onChange={v => updateField('autoGenerateDossier', v)} label="Gerar dossiê automaticamente após cálculo" />
          </div>
        </div>

        {/* Notifications */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="p-5 border-b border-slate-100 flex items-center gap-3">
            <Bell className="h-5 w-5 text-red-500" />
            <div><p className="font-semibold text-slate-900">Notificações</p><p className="text-xs text-slate-500">Alertas e avisos do sistema</p></div>
          </div>
          <div className="p-5 space-y-3">
            <Toggle value={settings.notifyImportCompleted !== false} onChange={v => updateField('notifyImportCompleted', v)} label="Notificar importação concluída" />
            <Toggle value={settings.notifyParsingErrors !== false} onChange={v => updateField('notifyParsingErrors', v)} label="Notificar erros de parsing" />
            <Toggle value={settings.notifyOpenIssues !== false} onChange={v => updateField('notifyOpenIssues', v)} label="Notificar pendências abertas" />
            <Toggle value={settings.notifyCalcCompleted !== false} onChange={v => updateField('notifyCalcCompleted', v)} label="Notificar cálculo concluído" />
          </div>
        </div>

        {/* Save */}
        <div className="flex justify-end">
          <Button onClick={() => save(settings)} disabled={saving} className="min-w-[200px]">
            {saving ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Salvando...</> : <><Settings className="mr-2 h-4 w-4" />Salvar Configurações</>}
          </Button>
        </div>
      </div>
    </div>
  );
}
