import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class TransitionCreditsService {
  constructor(private readonly prisma: PrismaService) {}

  async findAll(branchId?: string, status?: string, calculationId?: string, page = 1, limit = 50) {
    const skip = (page - 1) * limit;
    const where: Prisma.TransitionCreditLotWhereInput = {
      ...(branchId ? { branchId } : {}),
      ...(status ? { status: status as 'OPEN' | 'PARTIALLY_USED' | 'FULLY_USED' | 'BLOCKED' } : {}),
      ...(calculationId ? { calculationId } : {}),
    };
    const [lots, total] = await Promise.all([
      this.prisma.transitionCreditLot.findMany({
        where,
        skip,
        take: limit,
        include: {
          stockSnapshotItem: { select: { rawSku: true, rawDescription: true, quantity: true } },
          nfeItem: { select: { cProd: true, xProd: true, vICMSST: true, vFCPST: true, nfeDocument: { select: { numero: true, chaveAcesso: true, dataEmissao: true, nomeEmitente: true } } } },
          taxTransitionRule: { select: { name: true, calcMethod: true } },
          _count: { select: { ledgerEntries: true } },
        },
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.transitionCreditLot.count({ where }),
    ]);
    return { lots, total, page, limit };
  }

  async findOne(id: string) {
    const lot = await this.prisma.transitionCreditLot.findUnique({
      where: { id },
      include: {
        stockSnapshotItem: true,
        nfeItem: { include: { nfeDocument: true } },
        taxTransitionRule: true,
        ledgerEntries: { orderBy: { createdAt: 'asc' } },
      },
    });
    if (!lot) throw new NotFoundException(`Lote de crédito ${id} não encontrado`);
    return lot;
  }

  async adjustCredit(id: string, amount: number, notes: string) {
    const lot = await this.findOne(id);
    if (lot.status === 'FULLY_USED') throw new BadRequestException('Lote já totalmente utilizado');

    await this.prisma.transitionCreditLedgerEntry.create({
      data: {
        branchId: lot.branchId,
        transitionCreditLotId: id,
        entryType: 'MANUAL_ADJUSTMENT',
        amount: new Prisma.Decimal(amount),
        referenceType: 'MANUAL',
        notes,
        isAutoGenerated: false,
      },
    });

    return { message: 'Ajuste registrado com sucesso' };
  }

  async blockCredit(id: string, notes: string) {
    const lot = await this.findOne(id);
    if (lot.status === 'BLOCKED') throw new BadRequestException('Lote já bloqueado');

    await this.prisma.$transaction(async (tx) => {
      await tx.transitionCreditLot.update({
        where: { id },
        data: { status: 'BLOCKED' },
      });
      await tx.transitionCreditLedgerEntry.create({
        data: {
          branchId: lot.branchId,
          transitionCreditLotId: id,
          entryType: 'BLOCKED',
          amount: lot.creditableAmount.neg(),
          referenceType: 'MANUAL',
          notes,
          isAutoGenerated: false,
        },
      });
    });

    return { message: 'Lote bloqueado com sucesso' };
  }

  async getLedger(branchId?: string, lotId?: string, entryType?: string, page = 1, limit = 100) {
    const skip = (page - 1) * limit;
    const where: Prisma.TransitionCreditLedgerEntryWhereInput = {
      ...(branchId ? { branchId } : {}),
      ...(lotId ? { transitionCreditLotId: lotId } : {}),
      ...(entryType ? { entryType: entryType as 'GENERATED' | 'MANUAL_ADJUSTMENT' | 'USED' | 'BLOCKED' | 'REVERSED' } : {}),
    };

    const [entries, total] = await Promise.all([
      this.prisma.transitionCreditLedgerEntry.findMany({
        where,
        skip,
        take: limit,
        include: {
          transitionCreditLot: {
            select: { stockSnapshotItem: { select: { rawSku: true, rawDescription: true } }, taxTransitionRule: { select: { name: true } } },
          },
        },
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.transitionCreditLedgerEntry.count({ where }),
    ]);

    return { entries, total, page, limit };
  }

  async getBalance(branchId: string) {
    const result = await this.prisma.transitionCreditLedgerEntry.groupBy({
      by: ['entryType'],
      where: { branchId },
      _sum: { amount: true },
    });

    let generated = 0;
    let used = 0;
    let blocked = 0;
    let adjustments = 0;
    let reversed = 0;

    for (const row of result) {
      const val = parseFloat(String(row._sum.amount ?? 0));
      switch (row.entryType) {
        case 'GENERATED': generated += val; break;
        case 'USED': used += val; break;
        case 'BLOCKED': blocked += val; break;
        case 'MANUAL_ADJUSTMENT': adjustments += val; break;
        case 'REVERSED': reversed += val; break;
      }
    }

    const available = generated + adjustments + used + blocked + reversed;

    return {
      branchId,
      totalGenerated: generated,
      totalUsed: Math.abs(used),
      totalBlocked: Math.abs(blocked),
      totalAdjustments: adjustments,
      totalReversed: Math.abs(reversed),
      available: Math.max(0, available),
    };
  }
}
